### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by robuuuste** [AggieNateHarris/ImplingSaver#1]
Hi, great plugin for clue scroll enthousiasts :) I do have a few suggestions.

- Add Nature impling jar for hard clues, they are currently the cheapest jar to obtain hard clue scrolls from.
- Would it be possible for the plugin to check the bank for clue scrolls? Right now it doesn't hide them if you have a clue in the bank.
- I think it would be better if the plugin would just hide/remove the "Loot" menu option on the item instead of hiding the item itself. I think it's a bit weird to have your inventory full of invisible items. It also glitches when switching tabs.
![13-11-2022_21-32-23](https://user-images.githubusercontent.com/91341050/201543289-7f01920f-051c-4089-af51-6bc41e35661a.gif)

**Comment by AggieNateHarris** [comment]
Thanks for the feedback! I'll work on the changes once I get a chance.

- I'll add nature impling, as well as crystal imps for elites.
- Removing the option while you have a clue in the bank I feel could cause frustration or confusion for users if they turned this on at one point, forgot about it, and are hunting implings for other loot at some later point and don't know why they can't open their jars.
- I'm new to the runelite api, I'll poke around a bit and try to find how to remove menu options

**Comment by ETalanian** [comment]
Big +1 on just hiding the loot option.  I got this plugin a couple weeks ago and just saw it in action for the first time, I was SO confused lmao
