### ISSUE TITLE
This plugin is no longer needed

### ISSUE THREAD

**Issue by Nightfirecat** [AggieNateHarris/ImplingSaver#13]
As of the [August 16 2023 game update](https://secure.runescape.com/m=news/desert-treasure-ii-changes--more-?oldschool=1) the game will prompt you before opening an impling jar which could grant you a clue that you're already carrying:

> As of today’s update, attempting to open an Impling Jar with a Clue in your Inventory of the same tier that the Impling could give, you’ll be given a warning.

Hence, this plugin grants no extra benefit over the now-default behavior that all players enjoy.

**Comment by TheLope** [comment]
@Nightfirecat After some consideration I believe the plugin still has a use case for tracking clues in the bank. The base-game feature only checks the player's inventory

**Comment by Nightfirecat** [comment]
I wasn't aware the ingame feature didn't take banked clues into account, that's a valid case.
