### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by WholesomeDogg0** [AggieNateHarris/ImplingSaver#9]
Plugin used to work and doesn't now. Tried reinstalling and imps still show up in invent with respective clue tier. Checked the toggle options and nothing happens

**Comment by crab-pancake** [comment]
are the (non-hidden) jars in your invent left click open or use? the plugin was recently modified to update the click option when you have a clue in your invent, rather than hiding them entirely

**Comment by WholesomeDogg0** [comment]
Ohhh I didn't even check! I'll take a look later when I get another clue
